const path = require('path');
const fs = require('fs');

const projectRoot = __dirname;
const workspaceRoot = path.resolve(projectRoot, '../..');

/**
 * Parse KEY=VALUE dotenv lines (no dependency). Skips comments/blank.
 * @param {string} src
 * @returns {Record<string, string>}
 */
function parseDotEnv(src) {
  /** @type {Record<string, string>} */
  const out = {};
  for (const raw of src.split(/\r?\n/)) {
    const line = raw.trim();
    if (!line || line.startsWith('#')) continue;
    const eq = line.indexOf('=');
    if (eq <= 0) continue;
    const key = line.slice(0, eq).trim();
    let val = line.slice(eq + 1).trim();
    if (
      (val.startsWith('"') && val.endsWith('"')) ||
      (val.startsWith("'") && val.endsWith("'"))
    ) {
      val = val.slice(1, -1);
    }
    out[key] = val;
  }
  return out;
}

/**
 * Load companion.env.local (NOT .env* — Expo require.context would Babel-parse those)
 * and write a gitignored seed module for __DEV__ SecureStore seeding.
 */
function syncCompanionDevSeed() {
  const companionPath = path.join(projectRoot, 'companion.env.local');
  const genPath = path.join(projectRoot, 'src/credentials/companionDevSeed.generated.ts');
  /** @type {Record<string, string>} */
  let parsed = {};
  if (fs.existsSync(companionPath)) {
    parsed = parseDotEnv(fs.readFileSync(companionPath, 'utf8'));
    Object.assign(process.env, parsed);
  }

  const provider = parsed['COMPANION_PORTAL_PROVIDER'];
  const baseUrl = parsed['COMPANION_PORTAL_BASE_URL'];
  const username = parsed['COMPANION_PORTAL_USERNAME'];
  const password = parsed['COMPANION_PORTAL_PASSWORD'];
  const studentExternalId = parsed['COMPANION_STUDENT_EXTERNAL_ID'] || 'dev-student';
  const sourceId = parsed['COMPANION_SOURCE_ID'] || 'dev-source';

  const complete =
    provider &&
    baseUrl &&
    username &&
    password &&
    ['canvas', 'skyward', 'aeries'].includes(provider);

  const seedLiteral = complete
    ? JSON.stringify({
        provider,
        baseUrl,
        username,
        password,
        studentExternalId,
        sourceId,
      })
    : 'null';

  const contents = `/**
 * AUTO-GENERATED by metro.config.js from companion.env.local — do not edit.
 * Gitignored. Never commit. Production builds should see null.
 */
import type { ICompanionDevPortalSeed } from './devCredentialSeed';

export const COMPANION_DEV_SEED: ICompanionDevPortalSeed | null = ${seedLiteral};
`;
  fs.mkdirSync(path.dirname(genPath), { recursive: true });
  fs.writeFileSync(genPath, contents);
}

syncCompanionDevSeed();

/** @type {import('expo/metro-config').MetroConfig} */
const { getDefaultConfig } = require('expo/metro-config');
const config = getDefaultConfig(projectRoot);

// SDK 57: on-demand filesystem handles pnpm symlinks automatically —
// no watchFolders or nodeModulesPaths needed for monorepo resolution.
// Point directly at src/ so Metro compiles TS directly without dist/.
// (dist/ is gitignored and absent on EAS cold builds.)
config.resolver.extraNodeModules = {
  '@scholaracle/contracts': path.resolve(projectRoot, '../contracts/src'),
  '@scholaracle/scraper-core': path.resolve(projectRoot, '../scraper-core/src'),
};

// Never pull companion secret files into the JS graph
config.resolver.blockList = [
  /(^|[/\\])companion\.env\.local$/,
  /(^|[/\\])\.env\.companion/,
];

module.exports = config;
