const path = require('path');
const fs = require('fs');

const projectRoot = __dirname;
const workspaceRoot = path.resolve(projectRoot, '../..');

/**
 * Parse KEY=VALUE dotenv lines (no dependency). Skips comments/blank.
 * @param {string} src
 * @returns {Record<string, string>}
 */
function parseDotEnv(src) {
  /** @type {Record<string, string>} */
  const out = {};
  for (const raw of src.split(/\r?\n/)) {
    const line = raw.trim();
    if (!line || line.startsWith('#')) continue;
    const eq = line.indexOf('=');
    if (eq <= 0) continue;
    const key = line.slice(0, eq).trim();
    let val = line.slice(eq + 1).trim();
    if (
      (val.startsWith('"') && val.endsWith('"')) ||
      (val.startsWith("'") && val.endsWith("'"))
    ) {
      val = val.slice(1, -1);
    }
    out[key] = val;
  }
  return out;
}

/**
 * Load companion.env.local (NOT .env* — Expo require.context would Babel-parse those)
 * and write a gitignored seed module for __DEV__ SecureStore seeding.
 */
function syncCompanionDevSeed() {
  const companionPath = path.join(projectRoot, 'companion.env.local');
  const genPath = path.join(projectRoot, 'src/credentials/companionDevSeed.generated.ts');
  /** @type {Record<string, string>} */
  let parsed = {};
  if (fs.existsSync(companionPath)) {
    parsed = parseDotEnv(fs.readFileSync(companionPath, 'utf8'));
    Object.assign(process.env, parsed);
  }

  const provider = parsed['COMPANION_PORTAL_PROVIDER'];
  const baseUrl = parsed['COMPANION_PORTAL_BASE_URL'];
  const username = parsed['COMPANION_PORTAL_USERNAME'];
  const password = parsed['COMPANION_PORTAL_PASSWORD'];
  const studentExternalId = parsed['COMPANION_STUDENT_EXTERNAL_ID'] || 'dev-student';
  const sourceId = parsed['COMPANION_SOURCE_ID'] || 'dev-source';

  const complete =
    provider &&
    baseUrl &&
    username &&
    password &&
    ['canvas', 'skyward', 'aeries'].includes(provider);

  const seedLiteral = complete
    ? JSON.stringify({
        provider,
        baseUrl,
        username,
        password,
        studentExternalId,
        sourceId,
      })
    : 'null';

  const contents = `/**
 * AUTO-GENERATED by metro.config.js from companion.env.local — do not edit.
 * Gitignored. Never commit. Production builds should see null.
 */
import type { ICompanionDevPortalSeed } from './devCredentialSeed';

export const COMPANION_DEV_SEED: ICompanionDevPortalSeed | null = ${seedLiteral};
`;
  fs.mkdirSync(path.dirname(genPath), { recursive: true });
  fs.writeFileSync(genPath, contents);
}

syncCompanionDevSeed();

// Emit environment info as the very first thing Metro logs — appears in EAS
// Xcode logs and helps diagnose Node.js version / path issues on CI.
process.stderr.write(`[metro.config] Node.js version: ${process.version}\n`);
process.stderr.write(`[metro.config] Platform: ${process.platform} ${process.arch}\n`);
process.stderr.write(`[metro.config] projectRoot: ${projectRoot}\n`);
process.stderr.write(`[metro.config] workspaceRoot: ${workspaceRoot}\n`);

/** @type {import('expo/metro-config').MetroConfig} */
let getDefaultConfig;
try {
  ({ getDefaultConfig } = require('expo/metro-config'));
} catch (err) {
  process.stderr.write(`[metro.config] FATAL: require('expo/metro-config') failed: ${err?.message}\n${err?.stack}\n`);
  throw err;
}

let config;
try {
  config = getDefaultConfig(projectRoot);
} catch (err) {
  process.stderr.write(`[metro.config] FATAL: getDefaultConfig() failed: ${err?.message}\n${err?.stack}\n`);
  throw err;
}

// Wrap the reporter to surface the real error if Metro's transformer fails to
// initialize. Metro's Bundler.js swallows _depGraph.ready() rejections via
// .catch(), leaving _transformer undefined. Re-throwing here propagates the
// real error through _initializedPromise so callers see it instead of the
// confusing downstream "Cannot read properties of undefined (reading 'transformFile')".
const _baseReporter = config.reporter;
config.reporter = {
  ...(_baseReporter || {}),
  update(event) {
    if (event.type === 'transformer_load_failed') {
      const err = event.error ?? new Error('Metro transformer failed to load (unknown error)');
      process.stderr.write('\n=== METRO_INIT_FAILURE ===\n');
      process.stderr.write(`type: ${event.type}\n`);
      process.stderr.write(`message: ${String(err?.message ?? err)}\n`);
      process.stderr.write(`stack:\n${err?.stack ?? '(no stack)'}\n`);
      process.stderr.write('=== END METRO_INIT_FAILURE ===\n\n');
      // Rethrowing causes _initializedPromise to reject, propagating the real
      // error to every caller of ready() / transformFile().
      throw err;
    }
    if (_baseReporter && typeof _baseReporter.update === 'function') {
      _baseReporter.update.call(_baseReporter, event);
    }
  },
};

// Limit watchFolders to only what the mobile app needs. getDefaultConfig adds
// ALL monorepo packages which causes Metro to crawl large backend codebases
// unnecessarily and can trigger fileMap.build() failures on EAS cold builds.
const contractsSrc = path.resolve(projectRoot, '../contracts/src');
const scraperCoreSrc = path.resolve(projectRoot, '../scraper-core/src');
const candidateWatchFolders = [
  path.join(workspaceRoot, 'node_modules'),
  contractsSrc,
  scraperCoreSrc,
];
config.watchFolders = candidateWatchFolders.filter((dir) => {
  const exists = fs.existsSync(dir);
  console.log(`[metro.config] watchFolder ${exists ? '✓' : '✗'} ${dir}`);
  return exists;
});

// Alias workspace packages directly to their src/ directories so Metro
// compiles TypeScript on the fly without needing pre-built dist/.
config.resolver.extraNodeModules = {
  '@scholaracle/contracts': contractsSrc,
  '@scholaracle/scraper-core': scraperCoreSrc,
};

// Never pull companion secret files into the JS graph
config.resolver.blockList = [
  /(^|[/\\])companion\.env\.local$/,
  /(^|[/\\])\.env\.companion/,
];

console.log('[metro.config] Configured watchFolders:', config.watchFolders);
console.log('[metro.config] transformerPath:', config.transformerPath);

module.exports = config;
