const path = require('path');
const fs = require('fs');

const projectRoot = __dirname;
const workspaceRoot = path.resolve(projectRoot, '../..');

/**
 * Parse KEY=VALUE dotenv lines (no dependency). Skips comments/blank.
 * @param {string} src
 * @returns {Record<string, string>}
 */
function parseDotEnv(src) {
  /** @type {Record<string, string>} */
  const out = {};
  for (const raw of src.split(/\r?\n/)) {
    const line = raw.trim();
    if (!line || line.startsWith('#')) continue;
    const eq = line.indexOf('=');
    if (eq <= 0) continue;
    const key = line.slice(0, eq).trim();
    let val = line.slice(eq + 1).trim();
    if (
      (val.startsWith('"') && val.endsWith('"')) ||
      (val.startsWith("'") && val.endsWith("'"))
    ) {
      val = val.slice(1, -1);
    }
    out[key] = val;
  }
  return out;
}

/**
 * Load companion.env.local and write a gitignored seed module for __DEV__ SecureStore seeding.
 */
function syncCompanionDevSeed() {
  try {
    const companionPath = path.join(projectRoot, 'companion.env.local');
    const genPath = path.join(
      projectRoot,
      'src/credentials/companionDevSeed.generated.ts',
    );
    /** @type {Record<string, string>} */
    let parsed = {};
    if (fs.existsSync(companionPath)) {
      parsed = parseDotEnv(fs.readFileSync(companionPath, 'utf8'));
      Object.assign(process.env, parsed);
    }

    const provider = parsed['COMPANION_PORTAL_PROVIDER'];
    const baseUrl = parsed['COMPANION_PORTAL_BASE_URL'];
    const username = parsed['COMPANION_PORTAL_USERNAME'];
    const password = parsed['COMPANION_PORTAL_PASSWORD'];
    const studentExternalId =
      parsed['COMPANION_STUDENT_EXTERNAL_ID'] || 'dev-student';
    const sourceId = parsed['COMPANION_SOURCE_ID'] || 'dev-source';

    const complete =
      provider &&
      baseUrl &&
      username &&
      password &&
      ['canvas', 'skyward', 'aeries'].includes(provider);

    const seedLiteral = complete
      ? JSON.stringify({
          provider,
          baseUrl,
          username,
          password,
          studentExternalId,
          sourceId,
        })
      : 'null';

    const contents = `/**
 * AUTO-GENERATED by metro.config.js from companion.env.local — do not edit.
 * Gitignored. Never commit. Production builds should see null.
 */
import type { ICompanionDevPortalSeed } from './devCredentialSeed';

export const COMPANION_DEV_SEED: ICompanionDevPortalSeed | null = ${seedLiteral};
`;
    fs.mkdirSync(path.dirname(genPath), { recursive: true });
    fs.writeFileSync(genPath, contents);
  } catch (e) {
    // Non-fatal: production EAS builds don't need companion credentials.
    process.stderr.write(
      `[metro.config] syncCompanionDevSeed skipped: ${e?.message}\n`,
    );
  }
}

syncCompanionDevSeed();

process.stderr.write(`[metro.config] Node.js: ${process.version} ${process.platform} ${process.arch}\n`);
process.stderr.write(`[metro.config] projectRoot: ${projectRoot}\n`);
process.stderr.write(`[metro.config] workspaceRoot: ${workspaceRoot}\n`);

/** @type {import('expo/metro-config').MetroConfig} */
const { getDefaultConfig } = require('expo/metro-config');
const config = getDefaultConfig(projectRoot);

// === Monorepo watchFolders ===
// Use the full workspaceRoot so Metro can crawl all packages without needing
// per-package path filtering. This avoids Transformer.verifyRootExists()
// throwing on EAS when individual src/ dirs don't exist in the archive.
config.watchFolders = [workspaceRoot];

process.stderr.write(`[metro.config] watchFolders: [workspaceRoot]\n`);
process.stderr.write(`[metro.config] transformerPath: ${config.transformerPath}\n`);

// Explicitly disable Watchman — use Node.js fs API instead. On EAS macOS
// Tahoe images Watchman may be installed but broken, causing fileMap.build()
// to reject and leaving _transformer undefined.
config.resolver.useWatchman = false;

// Alias workspace packages directly to their src/ directories so Metro
// compiles TypeScript on the fly without needing pre-built dist/.
const contractsSrc = path.resolve(projectRoot, '../contracts/src');
const scraperCoreSrc = path.resolve(projectRoot, '../scraper-core/src');
config.resolver.extraNodeModules = {
  '@scholaracle/contracts': contractsSrc,
  '@scholaracle/scraper-core': scraperCoreSrc,
};

// Never pull companion secret files into the JS graph
config.resolver.blockList = [
  /(^|[/\\])companion\.env\.local$/,
  /(^|[/\\])\.env\.companion/,
];

// Surface the real init error instead of the confusing downstream TypeError.
// Metro's Bundler.js .catch() fires transformer_load_failed but resolves
// _initializedPromise (leaving _transformer undefined). Rethrowing here
// propagates the actual root cause to every await ready() caller.
const _baseReporter = config.reporter;
config.reporter = {
  ...(_baseReporter || {}),
  update(event) {
    if (event.type === 'transformer_load_failed') {
      const err =
        event.error ?? new Error('Metro transformer failed to load');
      process.stderr.write('\n=== METRO_INIT_FAILURE ===\n');
      process.stderr.write(`message: ${String(err?.message ?? err)}\n`);
      process.stderr.write(`stack:\n${err?.stack ?? '(no stack)'}\n`);
      process.stderr.write('=== END METRO_INIT_FAILURE ===\n\n');
      throw err;
    }
    if (_baseReporter && typeof _baseReporter.update === 'function') {
      _baseReporter.update.call(_baseReporter, event);
    }
  },
};

module.exports = config;
